name: BCREGISTRY UI CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  bcregistry-ui-ci:
    uses: pwei1018/bcregistry-sre/.github/workflows/frontend-ci.yaml@main
    with:
      app_name: "bcregistry"
      working_directory: "."
      codecov_flag: ""